#!/bin/bash
# Generates /opt/agent-zero/.env from Nebius MysteryBox.
# Run on any machine with nebius CLI authenticated and jq installed.
# Usage: ./generate-env.sh [output-path]

set -euo pipefail

SECRET_ID="mbsec-e00rc2pb5nrjrjs7k7"
OUTPUT="${1:-/opt/agent-zero/.env}"

command -v nebius >/dev/null || { echo "Error: nebius CLI not found" >&2; exit 1; }
command -v jq     >/dev/null || { echo "Error: jq not found (apt install jq)" >&2; exit 1; }

get() {
  nebius mysterybox payload get-by-key \
    --secret-id "$SECRET_ID" \
    --key "$1" \
    --format json 2>/dev/null \
    | jq -r '.data.string_value // empty'
}

echo "Fetching secrets from MysteryBox $SECRET_ID ..."

AUTH_LOGIN=$(get AUTH_LOGIN)
AUTH_PASSWORD=$(get AUTH_PASSWORD)
ANTHROPIC_API_KEY=$(get ANTHROPIC_API_KEY)
OPENAI_API_KEY=$(get OPENAI_API_KEY)
GEMINI_API_KEY=$(get GEMINI_API_KEY)
OPENROUTER_API_KEY=$(get OPENROUTER_API_KEY)
DEEPINFRA_API_KEY=$(get DEEPINFRA_API_KEY)
NEBIUS_API_KEY=$(get NEBIUS_API_KEY)
AWS_BEARER_TOKEN_BEDROCK=$(get AWS_BEARER_TOKEN_BEDROCK)
TAVILY_API_KEY=$(get TAVILY_API_KEY)
BRAVE_API_KEY=$(get BRAVE_API_KEY)
PERPLEXITY_API_KEY=$(get PERPLEXITY_API_KEY)
CONTEXT7_API_KEY=$(get CONTEXT7_API_KEY)
VIRUSTOTAL_API_KEY=$(get VIRUSTOTAL_API_KEY)
TELEGRAM_BOT_TOKEN=$(get TELEGRAM_BOT_TOKEN)
LANGSMITH_API_KEY=$(get LANGSMITH_API_KEY)
GITHUB_PAT=$(get GITHUB_PAT)
GHCR_PAT=$(get GHCR_PAT)
SKILL_SCANNER_LLM_API_KEY=$(get SKILL_SCANNER_LLM_API_KEY)
SKILL_SCANNER_LLM_MODEL=$(get SKILL_SCANNER_LLM_MODEL)

mkdir -p "$(dirname "$OUTPUT")"

cat > "$OUTPUT" <<EOF
AUTH_LOGIN=${AUTH_LOGIN}
AUTH_PASSWORD=${AUTH_PASSWORD}

A0_BASE_URL=https://helpa0.com

ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
OPENAI_API_KEY=${OPENAI_API_KEY}
GEMINI_API_KEY=${GEMINI_API_KEY}
OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
DEEPINFRA_API_KEY=${DEEPINFRA_API_KEY}
NEBIUS_API_KEY=${NEBIUS_API_KEY}
AWS_BEARER_TOKEN_BEDROCK=${AWS_BEARER_TOKEN_BEDROCK}

API_KEY_GOOGLE=${GEMINI_API_KEY}
API_KEY_BEDROCK=${AWS_BEARER_TOKEN_BEDROCK}
API_KEY_DEEPINFRA=${DEEPINFRA_API_KEY}

TAVILY_API_KEY=${TAVILY_API_KEY}
BRAVE_API_KEY=${BRAVE_API_KEY}
PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
CONTEXT7_API_KEY=${CONTEXT7_API_KEY}
VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY}

TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
LANGSMITH_API_KEY=${LANGSMITH_API_KEY}

GITHUB_PAT=${GITHUB_PAT}
GHCR_PAT=${GHCR_PAT}

SKILL_SCANNER_LLM_API_KEY=${SKILL_SCANNER_LLM_API_KEY}
SKILL_SCANNER_LLM_MODEL=${SKILL_SCANNER_LLM_MODEL}
EOF

chmod 600 "$OUTPUT"

echo "Written to $OUTPUT"
